enableTelemetry: false

enableTransparentWorkspaces: false

# plugins:
#   - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
#     spec: "@yarnpkg/plugin-typescript"

# pnpFallbackMode: all

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.1.1.cjs
