enableTelemetry: false

enableTransparentWorkspaces: false

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

pnpFallbackMode: all

yarnPath: .yarn/releases/yarn-3.1.1.cjs
